import { PageTemplate, Search } from "@/Components";
import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageTemplate>
        <h1> Encontre opções proximas a vs</h1>
        <Search />
        <h2>Descubra seu novo Delivery favorito.</h2>
      </PageTemplate>

      <h1 className="text-3xl font-bold underline">
        Hello Word, Allison Dev Pleno!
      </h1>
    </>
  );
};

export default Home;
